;;; events.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))
  (sb-ext:muffle-conditions sb-kernel:redefinition-with-defun)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.AG-UI")
    (cl:defpackage "CL-PROTOBUFS.AG-UI" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.AG-UI")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'events
    :syntax :proto3

    :package "ag_ui"
    :import '("google/protobuf/struct.proto"
    "patch.proto"
    "types.proto"))
)


;;; Top-Level enums

(pi:define-enum event-type
    ()
  (:text-message-start :index 0)
  (:text-message-content :index 1)
  (:text-message-end :index 2)
  (:tool-call-start :index 3)
  (:tool-call-args :index 4)
  (:tool-call-end :index 5)
  (:state-snapshot :index 6)
  (:state-delta :index 7)
  (:messages-snapshot :index 8)
  (:raw :index 9)
  (:custom :index 10)
  (:run-started :index 11)
  (:run-finished :index 12)
  (:run-error :index 13)
  (:step-started :index 14)
  (:step-finished :index 15)
  (:subagent-started :index 16)
  (:subagent-finished :index 17)
  (:subagent-error :index 18))

;;; Top-Level messages

(pi:define-message base-event
    ()
  ;; Fields
  (pi:define-oneof -timestamp (:synthetic-p t)
    (timestamp
     :index 2 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "timestamp"))
  (pi:define-oneof -raw-event (:synthetic-p t)
    (raw-event
     :index 3 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "rawEvent"))
  (type
   :index 1 :type event-type :kind :enum :label (:optional) :field-presence :implicit :json-name "type" :default :text-message-start)
  (metadata
   :index 4 :type cl-protobufs.google.protobuf::struct :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))

(pi:define-message text-message-start-event
    ()
  ;; Fields
  (pi:define-oneof -role (:synthetic-p t)
    (role
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "role"))
  (pi:define-oneof -name (:synthetic-p t)
    (name
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "name"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (message-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "messageId"))

(pi:define-message text-message-content-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (message-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "messageId")
  (delta
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "delta"))

(pi:define-message text-message-end-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (message-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "messageId"))

(pi:define-message tool-call-start-event
    ()
  ;; Fields
  (pi:define-oneof -parent-message-id (:synthetic-p t)
    (parent-message-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "parentMessageId"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (tool-call-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "toolCallId")
  (tool-call-name
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "toolCallName"))

(pi:define-message tool-call-args-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (tool-call-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "toolCallId")
  (delta
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "delta"))

(pi:define-message tool-call-end-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (tool-call-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "toolCallId"))

(pi:define-message state-snapshot-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (snapshot
   :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "snapshot"))

(pi:define-message state-delta-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (delta
   :index 2 :type cl-protobufs.ag-ui::json-patch-operation :kind :message :label (:repeated :list) :field-presence :implicit :json-name "delta"))

(pi:define-message messages-snapshot-event
    ()
  ;; Fields
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (messages
   :index 2 :type cl-protobufs.ag-ui::message :kind :message :label (:repeated :list) :field-presence :implicit :json-name "messages"))

(pi:define-message raw-event
    ()
  ;; Fields
  (pi:define-oneof -source (:synthetic-p t)
    (source
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "source"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (event
   :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "event"))

(pi:define-message custom-event
    ()
  ;; Fields
  (pi:define-oneof -value (:synthetic-p t)
    (value
     :index 3 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "value"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (name
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "name"))

(pi:define-message run-started-event
    ()
  ;; Fields
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (thread-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "threadId")
  (run-id
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "runId"))

(pi:define-message usage
    ()
  ;; Fields
  (pi:define-oneof -provider (:synthetic-p t)
    (provider
     :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "provider"))
  (pi:define-oneof -model (:synthetic-p t)
    (model
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "model"))
  (pi:define-oneof -input-tokens (:synthetic-p t)
    (input-tokens
     :index 3 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "inputTokens"))
  (pi:define-oneof -output-tokens (:synthetic-p t)
    (output-tokens
     :index 4 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "outputTokens"))
  (pi:define-oneof -total-tokens (:synthetic-p t)
    (total-tokens
     :index 5 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "totalTokens"))
  (pi:define-oneof -reasoning-tokens (:synthetic-p t)
    (reasoning-tokens
     :index 6 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "reasoningTokens"))
  (pi:define-oneof -cached-input-tokens (:synthetic-p t)
    (cached-input-tokens
     :index 7 :type cl-protobufs:int64 :kind :scalar :label (:optional) :field-presence :explicit :json-name "cachedInputTokens")))

(pi:define-message run-finished-event
    ()
  ;; Fields
  (pi:define-oneof -result (:synthetic-p t)
    (result
     :index 4 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "result"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (thread-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "threadId")
  (run-id
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "runId")
  (outcome
   :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "outcome")
  (interrupts
   :index 6 :type cl-protobufs.ag-ui::interrupt :kind :message :label (:repeated :list) :field-presence :implicit :json-name "interrupts")
  (usage
   :index 7 :type usage :kind :message :label (:repeated :list) :field-presence :implicit :json-name "usage"))

(pi:define-message run-error-event
    ()
  ;; Fields
  (pi:define-oneof -code (:synthetic-p t)
    (code
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "code"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (message
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "message")
  (usage
   :index 4 :type usage :kind :message :label (:repeated :list) :field-presence :implicit :json-name "usage"))

(pi:define-message step-started-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (step-name
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "stepName"))

(pi:define-message step-finished-event
    ()
  ;; Fields
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (step-name
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "stepName"))

(pi:define-message text-message-chunk-event
    ()
  ;; Fields
  (pi:define-oneof -message-id (:synthetic-p t)
    (message-id
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "messageId"))
  (pi:define-oneof -role (:synthetic-p t)
    (role
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "role"))
  (pi:define-oneof -delta (:synthetic-p t)
    (delta
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "delta"))
  (pi:define-oneof -name (:synthetic-p t)
    (name
     :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "name"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 6 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent"))

(pi:define-message tool-call-chunk-event
    ()
  ;; Fields
  (pi:define-oneof -tool-call-id (:synthetic-p t)
    (tool-call-id
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "toolCallId"))
  (pi:define-oneof -tool-call-name (:synthetic-p t)
    (tool-call-name
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "toolCallName"))
  (pi:define-oneof -parent-message-id (:synthetic-p t)
    (parent-message-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "parentMessageId"))
  (pi:define-oneof -delta (:synthetic-p t)
    (delta
     :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "delta"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 6 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent"))

(pi:define-message subagent-started-event
    ()
  ;; Fields
  (pi:define-oneof -description (:synthetic-p t)
    (description
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "description"))
  (pi:define-oneof -parent-subagent-run-id (:synthetic-p t)
    (parent-subagent-run-id
     :index 5 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "parentSubagentRunId"))
  (pi:define-oneof -parent-tool-call-id (:synthetic-p t)
    (parent-tool-call-id
     :index 6 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "parentToolCallId"))
  (pi:define-oneof -parent-message-id (:synthetic-p t)
    (parent-message-id
     :index 7 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "parentMessageId"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (subagent-run-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "subagentRunId")
  (name
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "name"))

(pi:define-message subagent-finished-event
    ()
  ;; Fields
  (pi:define-oneof -result (:synthetic-p t)
    (result
     :index 3 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "result"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (subagent-run-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "subagentRunId")
  (outcome
   :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "outcome")
  (interrupt-ids
   :index 5 :type cl:string :kind :scalar :label (:repeated :list) :field-presence :implicit :json-name "interruptIds"))

(pi:define-message subagent-error-event
    ()
  ;; Fields
  (pi:define-oneof -code (:synthetic-p t)
    (code
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "code"))
  (base-event
   :index 1 :type base-event :kind :message :label (:optional) :field-presence :explicit :json-name "baseEvent")
  (subagent-run-id
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "subagentRunId")
  (message
   :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "message"))

(pi:define-message event
    ()
  ;; Fields
  (pi:define-oneof event ()
    (text-message-start
     :index 1 :type text-message-start-event :kind :message :label (:optional) :field-presence :explicit :json-name "textMessageStart")
    (text-message-content
     :index 2 :type text-message-content-event :kind :message :label (:optional) :field-presence :explicit :json-name "textMessageContent")
    (text-message-end
     :index 3 :type text-message-end-event :kind :message :label (:optional) :field-presence :explicit :json-name "textMessageEnd")
    (tool-call-start
     :index 4 :type tool-call-start-event :kind :message :label (:optional) :field-presence :explicit :json-name "toolCallStart")
    (tool-call-args
     :index 5 :type tool-call-args-event :kind :message :label (:optional) :field-presence :explicit :json-name "toolCallArgs")
    (tool-call-end
     :index 6 :type tool-call-end-event :kind :message :label (:optional) :field-presence :explicit :json-name "toolCallEnd")
    (state-snapshot
     :index 7 :type state-snapshot-event :kind :message :label (:optional) :field-presence :explicit :json-name "stateSnapshot")
    (state-delta
     :index 8 :type state-delta-event :kind :message :label (:optional) :field-presence :explicit :json-name "stateDelta")
    (messages-snapshot
     :index 9 :type messages-snapshot-event :kind :message :label (:optional) :field-presence :explicit :json-name "messagesSnapshot")
    (raw
     :index 10 :type raw-event :kind :message :label (:optional) :field-presence :explicit :json-name "raw")
    (custom
     :index 11 :type custom-event :kind :message :label (:optional) :field-presence :explicit :json-name "custom")
    (run-started
     :index 12 :type run-started-event :kind :message :label (:optional) :field-presence :explicit :json-name "runStarted")
    (run-finished
     :index 13 :type run-finished-event :kind :message :label (:optional) :field-presence :explicit :json-name "runFinished")
    (run-error
     :index 14 :type run-error-event :kind :message :label (:optional) :field-presence :explicit :json-name "runError")
    (step-started
     :index 15 :type step-started-event :kind :message :label (:optional) :field-presence :explicit :json-name "stepStarted")
    (step-finished
     :index 16 :type step-finished-event :kind :message :label (:optional) :field-presence :explicit :json-name "stepFinished")
    (text-message-chunk
     :index 17 :type text-message-chunk-event :kind :message :label (:optional) :field-presence :explicit :json-name "textMessageChunk")
    (tool-call-chunk
     :index 18 :type tool-call-chunk-event :kind :message :label (:optional) :field-presence :explicit :json-name "toolCallChunk")
    (subagent-started
     :index 19 :type subagent-started-event :kind :message :label (:optional) :field-presence :explicit :json-name "subagentStarted")
    (subagent-finished
     :index 20 :type subagent-finished-event :kind :message :label (:optional) :field-presence :explicit :json-name "subagentFinished")
    (subagent-error
     :index 21 :type subagent-error-event :kind :message :label (:optional) :field-presence :explicit :json-name "subagentError")))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"events.proto" 'events)
)

(cl:export '(base-event
cached-input-tokens
code
custom
custom-event
delta
description
event
event-type
event-type-int-to-keyword
event-type-keyword-to-int
events
input-tokens
interrupt-ids
interrupts
message
message-id
messages
messages-snapshot
messages-snapshot-event
metadata
model
name
outcome
output-tokens
parent-message-id
parent-subagent-run-id
parent-tool-call-id
provider
raw
raw-event
reasoning-tokens
result
role
run-error
run-error-event
run-finished
run-finished-event
run-id
run-started
run-started-event
snapshot
source
state-delta
state-delta-event
state-snapshot
state-snapshot-event
step-finished
step-finished-event
step-name
step-started
step-started-event
subagent-error
subagent-error-event
subagent-finished
subagent-finished-event
subagent-run-id
subagent-started
subagent-started-event
text-message-chunk
text-message-chunk-event
text-message-content
text-message-content-event
text-message-end
text-message-end-event
text-message-start
text-message-start-event
thread-id
timestamp
tool-call-args
tool-call-args-event
tool-call-chunk
tool-call-chunk-event
tool-call-end
tool-call-end-event
tool-call-id
tool-call-name
tool-call-start
tool-call-start-event
total-tokens
type
usage
value))
