;;; patch.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))
  (sb-ext:muffle-conditions sb-kernel:redefinition-with-defun)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.AG-UI")
    (cl:defpackage "CL-PROTOBUFS.AG-UI" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.AG-UI")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'patch
    :syntax :proto3

    :package "ag_ui"
    :import '("google/protobuf/struct.proto"))
)


;;; Top-Level enums

(pi:define-enum json-patch-operation-type
    ()
  (:add :index 0)
  (:remove :index 1)
  (:replace :index 2)
  (:move :index 3)
  (:copy :index 4)
  (:test :index 5))

;;; Top-Level messages

(pi:define-message json-patch-operation
    ()
  ;; Fields
  (pi:define-oneof -from (:synthetic-p t)
    (from
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "from"))
  (pi:define-oneof -value (:synthetic-p t)
    (value
     :index 4 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "value"))
  (op
   :index 1 :type json-patch-operation-type :kind :enum :label (:optional) :field-presence :implicit :json-name "op" :default :add)
  (path
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "path"))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"patch.proto" 'patch)
)

(cl:export '(from
json-patch-operation
json-patch-operation-type
json-patch-operation-type-int-to-keyword
json-patch-operation-type-keyword-to-int
op
patch
path
value))
