;;; types.proto.lisp
;;;
;;; Generated by the protocol buffer compiler. DO NOT EDIT!

(cl:in-package #:common-lisp-user)

#+sbcl
(cl:progn
 (cl:eval-when (:compile-toplevel) (sb-ext:restrict-compiler-policy 'cl:debug 0 1))
 (cl:declaim (cl:optimize (sb-c:store-coverage-data 0))
  (sb-ext:muffle-conditions sb-kernel:redefinition-with-defun)))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
  (cl:unless (cl:find-package "CL-PROTOBUFS.AG-UI")
    (cl:defpackage "CL-PROTOBUFS.AG-UI" (:use)
                   (:local-nicknames (#:pi #:cl-protobufs.implementation)))))

(cl:in-package "CL-PROTOBUFS.AG-UI")

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:define-schema 'types
    :syntax :proto3

    :package "ag_ui"
    :import '("google/protobuf/struct.proto"))
)


;;; Top-Level messages

(pi:define-message tool-call
    ()
  ;; Nested messages

  (pi:define-message tool-call.function
      ()
    ;; Fields
    (name
     :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "name")
    (arguments
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "arguments"))
  ;; Fields
  (id
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "id")
  (type
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "type")
  (function
   :index 3 :type tool-call.function :kind :message :label (:optional) :field-presence :explicit :json-name "function")
  (metadata
   :index 4 :type cl-protobufs.google.protobuf::struct :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))

(pi:define-message input-content-data-source
    ()
  ;; Fields
  (value
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "value")
  (mime-type
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "mimeType"))

(pi:define-message input-content-url-source
    ()
  ;; Fields
  (pi:define-oneof -mime-type (:synthetic-p t)
    (mime-type
     :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "mimeType"))
  (value
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "value"))

(pi:define-message input-content-source
    ()
  ;; Fields
  (pi:define-oneof source ()
    (data
     :index 1 :type input-content-data-source :kind :message :label (:optional) :field-presence :explicit :json-name "data")
    (url
     :index 2 :type input-content-url-source :kind :message :label (:optional) :field-presence :explicit :json-name "url")))

(pi:define-message text-input-part
    ()
  ;; Fields
  (text
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "text"))

(pi:define-message image-input-part
    ()
  ;; Fields
  (pi:define-oneof -metadata (:synthetic-p t)
    (metadata
     :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))
  (source
   :index 1 :type input-content-source :kind :message :label (:optional) :field-presence :explicit :json-name "source"))

(pi:define-message audio-input-part
    ()
  ;; Fields
  (pi:define-oneof -metadata (:synthetic-p t)
    (metadata
     :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))
  (source
   :index 1 :type input-content-source :kind :message :label (:optional) :field-presence :explicit :json-name "source"))

(pi:define-message video-input-part
    ()
  ;; Fields
  (pi:define-oneof -metadata (:synthetic-p t)
    (metadata
     :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))
  (source
   :index 1 :type input-content-source :kind :message :label (:optional) :field-presence :explicit :json-name "source"))

(pi:define-message document-input-part
    ()
  ;; Fields
  (pi:define-oneof -metadata (:synthetic-p t)
    (metadata
     :index 2 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))
  (source
   :index 1 :type input-content-source :kind :message :label (:optional) :field-presence :explicit :json-name "source"))

(pi:define-message input-content
    ()
  ;; Fields
  (pi:define-oneof part ()
    (text
     :index 1 :type text-input-part :kind :message :label (:optional) :field-presence :explicit :json-name "text")
    (image
     :index 2 :type image-input-part :kind :message :label (:optional) :field-presence :explicit :json-name "image")
    (audio
     :index 3 :type audio-input-part :kind :message :label (:optional) :field-presence :explicit :json-name "audio")
    (video
     :index 4 :type video-input-part :kind :message :label (:optional) :field-presence :explicit :json-name "video")
    (document
     :index 5 :type document-input-part :kind :message :label (:optional) :field-presence :explicit :json-name "document")))

(pi:define-message message
    ()
  ;; Fields
  (pi:define-oneof -content (:synthetic-p t)
    (content
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "content"))
  (pi:define-oneof -name (:synthetic-p t)
    (name
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "name"))
  (pi:define-oneof -tool-call-id (:synthetic-p t)
    (tool-call-id
     :index 6 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "toolCallId"))
  (pi:define-oneof -error (:synthetic-p t)
    (error
     :index 7 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "error"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 10 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (id
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "id")
  (role
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "role")
  (tool-calls
   :index 5 :type tool-call :kind :message :label (:repeated :list) :field-presence :implicit :json-name "toolCalls")
  (content-parts
   :index 8 :type input-content :kind :message :label (:repeated :list) :field-presence :implicit :json-name "contentParts")
  (metadata
   :index 9 :type cl-protobufs.google.protobuf::struct :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))

(pi:define-message interrupt
    ()
  ;; Fields
  (pi:define-oneof -message (:synthetic-p t)
    (message
     :index 3 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "message"))
  (pi:define-oneof -tool-call-id (:synthetic-p t)
    (tool-call-id
     :index 4 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "toolCallId"))
  (pi:define-oneof -response-schema (:synthetic-p t)
    (response-schema
     :index 5 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "responseSchema"))
  (pi:define-oneof -expires-at (:synthetic-p t)
    (expires-at
     :index 6 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "expiresAt"))
  (pi:define-oneof -metadata (:synthetic-p t)
    (metadata
     :index 7 :type cl-protobufs.google.protobuf::value :kind :message :label (:optional) :field-presence :explicit :json-name "metadata"))
  (pi:define-oneof -subagent-run-id (:synthetic-p t)
    (subagent-run-id
     :index 8 :type cl:string :kind :scalar :label (:optional) :field-presence :explicit :json-name "subagentRunId"))
  (id
   :index 1 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "id")
  (reason
   :index 2 :type cl:string :kind :scalar :label (:optional) :field-presence :implicit :json-name "reason"))

(cl:eval-when (:compile-toplevel :load-toplevel :execute)
(pi:add-file-descriptor #P"types.proto" 'types)
)

(cl:export '(arguments
audio
audio-input-part
content
content-parts
data
document
document-input-part
error
expires-at
function
id
image
image-input-part
input-content
input-content-data-source
input-content-source
input-content-url-source
interrupt
message
metadata
mime-type
name
reason
response-schema
role
source
subagent-run-id
text
text-input-part
tool-call
tool-call-id
tool-call.function
tool-calls
type
types
url
value
video
video-input-part))
